# Generated by Django 4.2.30 on 2026-04-19 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('manga', 'user')},
        ),
    ]
